create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
