create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create sequence adresse_seq start with 1 increment by 1;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create sequence personne_seq start with 1 increment by 1;
create table adresse (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255), rue varchar2(255), ville varchar2(255), primary key (id));
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31) not null, numero number(19,0) not null, etat varchar2(255), nom varchar2(255), prenom varchar2(64), telephone varchar2(255), email varchar2(255), id_adresse number(19,0), primary key (numero));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create table adresse (id bigint generated by default as identity, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table commande (numero bigint generated by default as identity, date_commande date, primary key (numero));
create table commande_map_lignes_commande (commande_numero bigint not null, map_lignes_commande_commande_numero bigint not null, map_lignes_commande_num_ligne integer not null, map_lignes_commande_key integer not null, primary key (commande_numero, map_lignes_commande_key));
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table compte_client (num_compte bigint not null, num_client bigint not null);
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, produit_id bigint, primary key (commande_numero, num_ligne));
create table operation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
create table personne (type_personne varchar(31) not null, numero bigint generated by default as identity, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero));
create table produit (id bigint generated by default as identity, label varchar(255), prix double, primary key (id));
alter table commande_map_lignes_commande add constraint UK_q6yst2qbtgcj5kwxafid1e57f unique (map_lignes_commande_commande_numero, map_lignes_commande_num_ligne);
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table commande_map_lignes_commande add constraint FK34omqnemhv0wqei89bwu8gm61 foreign key (map_lignes_commande_commande_numero, map_lignes_commande_num_ligne) references ligne_commande;
alter table commande_map_lignes_commande add constraint FKpjeaw6oy3u1lhki63rlf74sso foreign key (commande_numero) references commande;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande;
alter table ligne_commande add constraint FK5ykb96p8me6913jyiwbe8nyj5 foreign key (produit_id) references produit;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create table adresse (id bigint generated by default as identity, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table commande (numero bigint generated by default as identity, date_commande date, primary key (numero));
create table commande_map_lignes_commande (commande_numero bigint not null, map_lignes_commande_commande_numero bigint not null, map_lignes_commande_num_ligne integer not null, map_lignes_commande_key integer not null, primary key (commande_numero, map_lignes_commande_key));
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table compte_client (num_compte bigint not null, num_client bigint not null);
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, produit_id bigint, primary key (commande_numero, num_ligne));
create table operation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
create table personne (type_personne varchar(31) not null, numero bigint generated by default as identity, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero));
create table produit (id bigint generated by default as identity, label varchar(255), prix double, primary key (id));
alter table commande_map_lignes_commande add constraint UK_q6yst2qbtgcj5kwxafid1e57f unique (map_lignes_commande_commande_numero, map_lignes_commande_num_ligne);
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table commande_map_lignes_commande add constraint FK34omqnemhv0wqei89bwu8gm61 foreign key (map_lignes_commande_commande_numero, map_lignes_commande_num_ligne) references ligne_commande;
alter table commande_map_lignes_commande add constraint FKpjeaw6oy3u1lhki63rlf74sso foreign key (commande_numero) references commande;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande;
alter table ligne_commande add constraint FK5ykb96p8me6913jyiwbe8nyj5 foreign key (produit_id) references produit;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create table adresse (id bigint generated by default as identity, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table commande (numero bigint generated by default as identity, date_commande date, primary key (numero));
create table commande_map_lignes_commande (commande_numero bigint not null, map_lignes_commande_commande_numero bigint not null, map_lignes_commande_num_ligne integer not null, map_lignes_commande_key integer not null, primary key (commande_numero, map_lignes_commande_key));
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table compte_client (num_compte bigint not null, num_client bigint not null);
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, produit_id bigint, primary key (commande_numero, num_ligne));
create table operation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
create table personne (type_personne varchar(31) not null, numero bigint generated by default as identity, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero));
create table produit (id bigint generated by default as identity, label varchar(255), prix double, primary key (id));
alter table commande_map_lignes_commande add constraint UK_q6yst2qbtgcj5kwxafid1e57f unique (map_lignes_commande_commande_numero, map_lignes_commande_num_ligne);
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table commande_map_lignes_commande add constraint FK34omqnemhv0wqei89bwu8gm61 foreign key (map_lignes_commande_commande_numero, map_lignes_commande_num_ligne) references ligne_commande;
alter table commande_map_lignes_commande add constraint FKpjeaw6oy3u1lhki63rlf74sso foreign key (commande_numero) references commande;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande;
alter table ligne_commande add constraint FK5ykb96p8me6913jyiwbe8nyj5 foreign key (produit_id) references produit;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create table adresse (id bigint generated by default as identity, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id));
create table commande (numero bigint generated by default as identity, date_commande date, primary key (numero));
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table compte_client (num_compte bigint not null, num_client bigint not null);
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, map_lignes_commande_key integer, primary key (commande_numero, num_ligne));
create table operation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
create table personne (type_personne varchar(31) not null, numero bigint generated by default as identity, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero));
create table produit (id bigint generated by default as identity, label varchar(255), prix double, primary key (id));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande;
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, map_lignes_commande_key integer, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create sequence adresse_seq start with 1 increment by  1;
create sequence compte_seq start with 1 increment by  1;
create sequence operation_seq start with 1 increment by  1;
create sequence personne_seq start with 1 increment by  1;
create table adresse (id number(19,0) not null, code_postal varchar2(255 char), rue varchar2(255 char), ville varchar2(255 char), primary key (id));
create table adresse_de_personne (id number(19,0) not null, code_postal varchar2(255 char), rue varchar2(255 char), ville varchar2(255 char), primary key (id));
create table commande (numero number(19,0) generated as identity, date_commande date, primary key (numero));
create table compte (numero number(19,0) not null, label varchar2(255 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table ligne_commande (num_ligne number(10,0) not null, quantite number(10,0), commande_numero number(19,0) not null, ref_produit number(19,0), primary key (commande_numero, num_ligne));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
create table personne (type_personne varchar2(31 char) not null, numero number(19,0) not null, etat varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), telephone varchar2(255 char), email varchar2(255 char), id_adresse number(19,0), primary key (numero));
create table produit (id number(19,0) generated as identity, label varchar2(255 char), prix double precision, primary key (id));
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne;
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande;
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse;
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table adresse_de_personne (id bigint not null, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table commande (numero bigint not null auto_increment, date_commande date, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table ligne_commande (num_ligne integer not null, quantite integer, commande_numero bigint not null, ref_produit bigint, primary key (commande_numero, num_ligne)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date_op date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), telephone varchar(255), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
create table produit (id bigint not null auto_increment, label varchar(255), prix double precision, primary key (id)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table adresse_de_personne add constraint FKbsng4prvgxw5cfa00s61e7jmo foreign key (id) references personne (numero);
alter table compte_client add constraint FKd7bi8a3nb8urkipsj0ug5lkdm foreign key (num_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table ligne_commande add constraint FKj563liwv9yrxkxr0dj6lgs11y foreign key (commande_numero) references commande (numero);
alter table ligne_commande add constraint FKjpaho0chkvl9d6arkc6asbt0b foreign key (ref_produit) references produit (id);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
