create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create sequence hibernate_sequence start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence hibernate_sequence start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence hibernate_sequence start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table employe (numero number(19,0) not null, email varchar2(255), nom varchar2(255), prenom varchar2(64), primary key (numero));
create sequence hibernate_sequence start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table employe (numero number(19,0) not null, email varchar2(255), nom varchar2(255), prenom varchar2(64), primary key (numero));
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date datetime(6), label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date datetime(6), label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, compte_numero bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKrhblg2ej3p9w20wtpdda24omv foreign key (compte_numero) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, compte_numero bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKrhblg2ej3p9w20wtpdda24omv foreign key (compte_numero) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, num_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FK1a5doyjrqncuqgp2decjxcc4k foreign key (num_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, numero_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKpw05bq479gov4hqp9n4l753q2 foreign key (numero_client) references client (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, num_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, num_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKbhxsypvlnd3a5ahku5beo1ams foreign key (num_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
