drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop sequence adresse_seq;
drop sequence compte_seq;
drop sequence operation_seq;
drop sequence personne_seq;
