drop table if exists compte;
drop table if exists employe;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table if exists compte;
drop table if exists employe;
