drop table if exists compte;
drop table if exists employe;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop sequence hibernate_sequence;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKrhblg2ej3p9w20wtpdda24omv;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKrhblg2ej3p9w20wtpdda24omv;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKpw05bq479gov4hqp9n4l753q2;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table client drop foreign key FKin9lm6s50fe989kbfpw7000t9;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table employe drop foreign key FKdbgp2j54tvxls2sa5vlm4ph6u;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
alter table client drop foreign key FKin9lm6s50fe989kbfpw7000t9;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table employe drop foreign key FKdbgp2j54tvxls2sa5vlm4ph6u;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
alter table client drop foreign key FKin9lm6s50fe989kbfpw7000t9;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table employe drop foreign key FKdbgp2j54tvxls2sa5vlm4ph6u;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKi046fphbc5l1h95vv49smx7da;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table adresse_de_personne drop foreign key FKbsng4prvgxw5cfa00s61e7jmo;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists adresse_de_personne;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table personne cascade constraints;
drop table toperation cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table personne cascade constraints;
drop table toperation cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table personne cascade constraints;
drop table toperation cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation_bank cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation_bank cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation_bank cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation_bank cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation_bank cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation_bank cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation_bank cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
drop table adresse cascade constraints;
drop table adresse_de_personne cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table operation cascade constraints;
drop table personne cascade constraints;
