drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table compte cascade constraints;
drop table toperation cascade constraints;
drop table if exists compte CASCADE ;
drop table if exists toperation CASCADE ;
drop table if exists compte CASCADE ;
drop table if exists toperation CASCADE ;
drop table if exists compte CASCADE ;
drop table if exists toperation CASCADE ;
drop table if exists compte CASCADE ;
drop table if exists operation CASCADE ;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence hibernate_sequence;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table compte_customer drop foreign key FK3iaf8jofis07oyiruv8qfpru3;
alter table compte_customer drop foreign key FK48bmxf9kapujcstxgmlgunv6n;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_customer;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table compte_customer cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
