create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(255), solde double precision, primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table toperation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table toperation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table toperation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table toperation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
alter table toperation add constraint FK2kfnv1krkqi53fw6ophhshq3n foreign key (num_compte) references compte;
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table operation (id_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create table compte (numero number(19,0) generated as identity, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by  1;
create table compte (numero number(19,0) not null, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by  1;
create table compte (numero number(19,0) not null, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) generated as identity, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by  1;
create sequence operation_seq start with 1 increment by  1;
create table compte (numero number(19,0) not null, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by  1;
create sequence operation_seq start with 1 increment by  1;
create table compte (numero number(19,0) not null, label varchar2(255 char), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255 char), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_operation number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_operation));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence hibernate_sequence start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence hibernate_sequence start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence hibernate_sequence start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence compte_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence compte_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence compte_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence compte_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 10 increment by 1;
create sequence operation_seq start with 100 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 10 increment by 1;
create sequence operation_seq start with 100 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 10 increment by 1;
create sequence operation_seq start with 100 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 10 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
create sequence compte_seq start with 1 increment by 1;
create sequence operation_seq start with 1 increment by 1;
create table compte (numero number(19,0) not null, label varchar2(255), solde double precision, primary key (numero));
create table operation (id_op number(19,0) not null, date_op date, label varchar2(255), montant double precision, num_compte number(19,0), primary key (id_op));
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
